name: ecom-py311
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.3=pyhc872135_0
  - python=3.11.13=hbff2529_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - tzdata=2025c=he532380_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.1
      - asgiref==3.11.0
      - babel==2.18.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - django==5.2.10
      - django-cors-headers==4.9.0
      - django-extra-views==0.16.0
      - django-haystack==3.3.0
      - django-oscar==4.1
      - django-phonenumber-field==8.4.0
      - django-tables2==2.7.0
      - django-treebeard==4.8.0
      - django-widget-tweaks==1.5.1
      - djangorestframework==3.16.1
      - factory-boy==3.3.3
      - faker==40.1.2
      - filelock==3.20.3
      - fsspec==2026.1.0
      - graphene==3.4.3
      - graphene-django==3.2.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.7
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==1.2.8
      - langchain-ollama==1.0.1
      - langsmith==0.6.8
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==1.26.4
      - ollama==0.6.1
      - orjson==3.11.7
      - packaging==26.0
      - pgvector==0.4.2
      - phonenumbers==9.0.22
      - pillow==12.1.0
      - promise==2.3
      - psycopg2-binary==2.9.11
      - purl==1.6
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sentence-transformers==5.2.2
      - shellingham==1.5.4
      - six==1.17.0
      - sqlparse==0.5.5
      - sympy==1.14.0
      - tenacity==9.1.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.2
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: /opt/miniconda3/envs/ecom-py311
