name: K8s Security Scan

on:
  push:
    paths:
      - 'k8s-manifests/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'k8s-manifests/**'
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          scan-ref: 'k8s-manifests'
          exit-code: '0' # Don't fail the build, just report
          severity: 'CRITICAL,HIGH'

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: k8s-manifests
          framework: kubernetes
          quiet: true
          # check: CKV_K8S_1,CKV_K8S_2 # Optional: specify checks
